export default [
  {
    material: ['cotton'],
    popularity: 20,
    title: 'Желтое платье из прошвы с открытой спинкой',
    description:
      'Платье из прошвы с V-образным вырезом по спинке. Модель дополнена бантами из основного материала, которые не регулируются. Предусмотрена подкладка из хлопка.',
    model: 'model-1',
    color: 'yellow',
    images: [
      {
        color: ['yellow', 'white'],
        original: 'd1.1.jpg',
        thumbnail: 'd1.1s.jpg',
      },
      {
        color: ['yellow'],
        original: 'd1.2.jpg',
        thumbnail: 'd1.2s.jpg',
      },
      {
        color: ['yellow'],
        original: 'd1.3.jpg',
        thumbnail: 'd1.3s.jpg',
      },
      {
        color: ['yellow', 'white'],
        original: 'd1.5.jpg',
        thumbnail: 'd1.5s.jpg',
      },
    ],
    size: {
      '42': 1,
      '44': 1,
      '46': 1,
      '48': 1,
      '50': 1,
    },
    price: 999,
    category: 'dress',
    globalCategory: 'femaleClothes',

    season: 'summer',
    createdAt: '2021-09-14T20:34:43.234Z',
    updatedAt: '2021-09-14T20:34:43.234Z',
    __v: 0,
    id: '614107630038b85604ae2661',
  },
  {
    material: ['cotton'],
    popularity: 19,
    title: 'Белое платье из прошвы с открытой спинкой',
    description:
      'Платье из прошвы с V-образным вырезом по спинке. Модель дополнена бантами из основного материала, которые не регулируются. Предусмотрена подкладка из хлопка.',
    model: 'model-1',
    color: 'white',
    images: [
      {
        color: ['white'],
        original: 'd1.6.jpg',
        thumbnail: 'd1.6s.jpg',
      },
      {
        color: ['white'],
        original: 'd1.1.jpg',
        thumbnail: 'd1.1s.jpg',
      },
      {
        color: ['yellow'],
        original: 'd1.2.jpg',
        thumbnail: 'd1.2s.jpg',
      },
      {
        color: ['yellow'],
        original: 'd1.3.jpg',
        thumbnail: 'd1.3s.jpg',
      },
      {
        color: ['yellow', 'white'],
        original: 'd1.5.jpg',
        thumbnail: 'd1.5s.jpg',
      },
    ],
    size: {
      '42': 1,
      '44': 0,
      '46': 1,
      '48': 0,
      '50': 0,
    },
    price: 999,
    category: 'dress',
    globalCategory: 'femaleClothes',
    season: 'summer',
    createdAt: '2021-09-14T20:51:10.758Z',
    updatedAt: '2021-09-19T11:02:53.526Z',
    __v: 0,
    id: '61410b3ea64fb459006d7e02',
  },
  {
    material: ['costumeFabric'],
    popularity: 18,
    title: 'Голубое платье с вырезом на спинке и расклешенной юбкой',
    description:
      'Романтичное платье с коротким рукавом и вырезом каре. Расклешенная юбка с драпировкой. На спинке вырез присобран на резинку.',
    model: 'model-2',
    color: 'blue',
    images: [
      {
        color: ['blue'],
        original: 'd2.1.jpg',
        thumbnail: 'd2.1s.jpg',
      },
      {
        color: ['blue'],
        original: 'd2.2.jpg',
        thumbnail: 'd2.2s.jpg',
      },
      {
        color: ['blue'],
        original: 'd2.3.jpg',
        thumbnail: 'd2.3s.jpg',
      },
      {
        color: ['blue'],
        original: 'd2.4.jpg',
        thumbnail: 'd2.4s.jpg',
      },
    ],
    size: {
      '42': 1,
      '44': 0,
      '46': 1,
      '48': 0,
      '50': 0,
    },
    price: 799,
    category: 'dress',
    globalCategory: 'femaleClothes',
    season: 'summer',
    createdAt: '2021-09-14T20:57:23.066Z',
    updatedAt: '2021-09-14T20:57:23.066Z',
    __v: 0,
    id: '61410cb3a64fb459006d7e08',
  },
  {
    material: ['cotton'],
    popularity: 16,
    title: 'Белое платье-трапеция из хлопка без рукавов',
    description:
      'Хлопковое платье-трапеция без рукавов с кокеткой из прошвы и воланом по низу. Застегивается на пуговицы по планке. Имеет хлопковую подкладку.',
    model: 'model-3',
    color: 'white',
    images: [
      {
        color: ['white'],
        original: 'd3.2.jpg',
        thumbnail: 'd3.2s.jpg',
      },
      {
        color: ['white'],
        original: 'd3.2.jpg',
        thumbnail: 'd3.2s.jpg',
      },
    ],
    size: {
      '42': 1,
      '44': 1,
      '46': 1,
      '48': 1,
      '50': 1,
    },
    price: 899,
    category: 'dress',
    globalCategory: 'femaleClothes',
    season: 'summer',
    createdAt: '2021-09-14T21:00:44.507Z',
    updatedAt: '2021-09-14T21:00:44.507Z',
    __v: 0,
    id: '61410d7ca64fb459006d7e0d',
  },
  {
    material: ['cotton'],
    popularity: 16,
    title: 'Голубое платье-трапеция из хлопка без рукавов',
    description:
      'Хлопковое платье-трапеция без рукавов с кокеткой из прошвы и воланом по низу. Застегивается на пуговицы по планке.',
    model: 'model-3',
    color: 'blue',
    images: [
      {
        color: ['blue'],
        original: 'd3.3.jpg',
        thumbnail: 'd3.3s.jpg',
      },
      {
        color: ['blue'],
        original: 'd3.4.jpg',
        thumbnail: 'd3.4s.jpg',
      },
    ],
    size: {
      '42': 1,
      '44': 1,
      '46': 1,
      '48': 1,
      '50': 1,
      '52': 0,
    },
    price: 899,
    category: 'dress',
    globalCategory: 'femaleClothes',
    season: 'summer',
    createdAt: '2021-09-14T21:02:45.759Z',
    updatedAt: '2021-09-14T21:02:45.759Z',
    __v: 0,
    id: '61410df5a64fb459006d7e10',
  },
  {
    material: ['soft'],
    popularity: 16,
    title: 'Платье с принтом и фигурным вырезом белое',
    description:
      'Женственное платье из софта с принтом. Модель приталенного силуэта с расклешенной юбкой и вафельной сборкой на поясе. Лиф выполнен на фиксированный запах и декорирован завязками. В изделии предусмотрена подкладка из хлопка.',
    model: 'model-4',
    color: 'white',
    images: [
      {
        color: ['white'],
        original: 'd4.1.jpg',
        thumbnail: 'd4.1s.jpg',
      },
      {
        color: ['white'],
        original: 'd4.2.jpg',
        thumbnail: 'd4.2s.jpg',
      },
      {
        color: ['white'],
        original: 'd4.3.jpg',
        thumbnail: 'd4.3s.jpg',
      },
    ],
    size: {
      '42': 1,
      '44': 1,
      '46': 1,
      '48': 1,
      '50': 1,
      '52': 0,
      '54': 1,
      '56': 1,
    },
    price: 899,
    category: 'dress',
    globalCategory: 'femaleClothes',
    season: 'summer',
    createdAt: '2021-09-14T21:06:44.772Z',
    updatedAt: '2021-09-14T21:06:44.772Z',
    __v: 0,
    id: '61410ee4a64fb459006d7e13',
  },
  {
    material: ['staple'],
    popularity: 21,
    title: 'Пудровое платье с цветочным принтом и фигурным вырезом',
    description:
      'Женственное платье из штапеля с цветочным принтом. Модель приталенного силуэта с расклешенной юбкой и вафельной сборкой на поясе. Лиф декорирован завязками. Запах зафиксирован.',
    model: 'model-4',
    color: 'pink',
    images: [
      {
        color: ['pink'],
        original: 'd4.4.jpg',
        thumbnail: 'd4.4s.jpg',
      },
      {
        color: ['pink'],
        original: 'd4.5.jpg',
        thumbnail: 'd4.5s.jpg',
      },
      {
        color: ['pink'],
        original: 'd4.6.jpg',
        thumbnail: 'd4.6s.jpg',
      },
      {
        color: ['pink'],
        original: 'd4.7.jpg',
        thumbnail: 'd4.7s.jpg',
      },
    ],
    size: {
      '42': 1,
      '44': 1,
      '46': 1,
      '48': 1,
      '50': 1,
      '52': 1,
    },
    price: 999,
    category: 'dress',
    globalCategory: 'femaleClothes',
    season: 'summer',
    createdAt: '2021-09-14T21:11:35.504Z',
    updatedAt: '2021-09-14T21:11:35.504Z',
    __v: 0,
    id: '61411007a64fb459006d7e17',
  },
  {
    material: ['costumeFabric'],
    popularity: 15,
    title: 'Брючный костюм с укороченным пиджаком бирюзовый',
    description:
      'Брючный костюм-двойка: укороченный двубортный пиджак и прямые брюки на резинке с карманами по бокам. Пиджак без подкладки.',
    model: 'model-5',
    color: 'green',
    images: [
      {
        color: ['green'],
        original: 's1.1.jpg',
        thumbnail: 's1.1s.jpg',
      },
      {
        color: ['green'],
        original: 's1.2.jpg',
        thumbnail: 's1.2s.jpg',
      },
      {
        color: ['green'],
        original: 's1.3.jpg',
        thumbnail: 's1.3s.jpg',
      },
      {
        color: ['green'],
        original: 's1.4.jpg',
        thumbnail: 's1.4s.jpg',
      },
      {
        color: ['green'],
        original: 's1.5.jpg',
        thumbnail: 's1.5s.jpg',
      },
      {
        color: ['green'],
        original: 's1.6.jpg',
        thumbnail: 's1.6s.jpg',
      },
    ],
    size: {
      '44': 1,
      '46': 1,
      '48': 1,
      '50': 1,
    },
    price: 1299,
    category: 'suit',
    globalCategory: 'femaleClothes',
    season: 'autumn/spring',
    createdAt: '2021-09-14T21:22:58.188Z',
    updatedAt: '2021-09-14T21:22:58.188Z',
    __v: 0,
    id: '614112b2a64fb459006d7e1c',
  },
  {
    material: ['costumeFabric'],
    popularity: 16,
    title: 'Брючный костюм с укороченным пиджаком черный',
    description:
      'Брючный костюм-двойка: укороченный двубортный пиджак и прямые брюки на резинке с карманами по бокам. Пиджак без подкладки.',
    model: 'model-5',
    color: 'black',
    images: [
      {
        color: ['black'],
        original: 's1.7.jpg',
        thumbnail: 's1.7s.jpg',
      },
      {
        color: ['black'],
        original: 's1.8.jpg',
        thumbnail: 's1.8s.jpg',
      },
      {
        color: ['black'],
        original: 's1.9.jpg',
        thumbnail: 's1.9s.jpg',
      },
      {
        color: ['black'],
        original: 's1.10.jpg',
        thumbnail: 's1.10s.jpg',
      },
      {
        color: ['black'],
        original: 's1.11.jpg',
        thumbnail: 's1.11s.jpg',
      },
    ],
    size: {
      '44': 1,
      '46': 1,
      '48': 1,
      '50': 1,
    },
    price: 1199,
    category: 'suit',
    globalCategory: 'femaleClothes',
    season: 'autumn/spring',
    createdAt: '2021-09-14T21:25:42.811Z',
    updatedAt: '2021-09-14T21:25:42.811Z',
    __v: 0,
    id: '61411356a64fb459006d7e23',
  },
  {
    material: ['costumeFabric'],
    popularity: 17,
    title: 'Вельветовый костюм цвета хаки из жакета на пуговицах и брюк',
    description:
      'Повседневный костюм из вельвета. Жакет на подкладке с воротником-стойкой и карманами по бокам. Застегивается на пуговицы по планке. Брюки с высокой посадкой и карманами в боковых швах. Застегиваются на молнию и пуговицу.',
    model: 'model-6',
    color: 'green',
    images: [
      {
        color: ['green'],
        original: 's2.1.jpg',
        thumbnail: 's2.1s.jpg',
      },
      {
        color: ['green'],
        original: 's2.2.jpg',
        thumbnail: 's2.2s.jpg',
      },
      {
        color: ['green'],
        original: 's2.3.jpg',
        thumbnail: 's2.3s.jpg',
      },
      {
        color: ['green'],
        original: 's2.4.jpg',
        thumbnail: 's2.4s.jpg',
      },
    ],
    size: {
      '44': 0,
      '46': 0,
      '48': 1,
      '50': 0,
      '52': 0,
      '54': 0,
    },
    price: 1299,
    category: 'suit',
    globalCategory: 'femaleClothes',
    season: 'autumn/spring',
    createdAt: '2021-09-14T21:28:23.400Z',
    updatedAt: '2021-09-14T21:28:23.400Z',
    __v: 0,
    id: '614113f7a64fb459006d7e29',
  },
  {
    material: ['costumeFabric'],
    popularity: 12,
    title: 'Вельветовый костюм из жакета на пуговицах и брюк бежевый',
    description:
      'Повседневный костюм из вельвета. Жакет на подкладке с воротником-стойкой и карманами по бокам. Застегивается на пуговицы по планке. Брюки с высокой посадкой и карманами в боковых швах. Застегиваются на молнию и пуговицу.',
    model: 'model-6',
    color: 'beige',
    images: [
      {
        color: ['beige'],
        original: 's2.5.jpg',
        thumbnail: 's2.5s.jpg',
      },
      {
        color: ['beige'],
        original: 's2.6.jpg',
        thumbnail: 's2.6s.jpg',
      },
      {
        color: ['beige'],
        original: 's2.7.jpg',
        thumbnail: 's2.7s.jpg',
      },
      {
        color: ['beige'],
        original: 's2.8.jpg',
        thumbnail: 's2.8s.jpg',
      },
      {
        color: ['beige'],
        original: 's2.9.jpg',
        thumbnail: 's2.9s.jpg',
      },
      {
        color: ['beige'],
        original: 's2.10.jpg',
        thumbnail: 's2.10s.jpg',
      },
    ],
    size: {
      '44': 1,
      '46': 1,
      '48': 1,
      '50': 1,
      '52': 1,
      '54': 1,
    },
    price: 1299,
    category: 'suit',
    globalCategory: 'femaleClothes',
    season: 'autumn/spring',
    createdAt: '2021-09-14T21:33:40.225Z',
    updatedAt: '2021-09-14T21:33:40.225Z',
    __v: 0,
    id: '61411534a64fb459006d7e2e',
  },
  {
    material: ['costumeFabric'],
    popularity: 10,
    title: 'Коричневые зауженные брюки на молнии',
    description:
      'Классические брюки со стрелками. Застёгиваются на молнию, пуговицу и два крючка. Для удобства в носке предусмотрены карманы.',
    model: 'model-7',
    color: 'brown',
    images: [
      {
        color: ['brown'],
        original: 'j1.1.jpg',
        thumbnail: 'j1.1s.jpg',
      },
      {
        color: ['brown'],
        original: 'j1.2.jpg',
        thumbnail: 'j1.2s.jpg',
      },
      {
        color: ['brown'],
        original: 'j1.3.jpg',
        thumbnail: 'j1.3s.jpg',
      },
      {
        color: ['brown'],
        original: 'j1.3.jpg',
        thumbnail: 'j1.3s.jpg',
      },
      {
        color: ['brown'],
        original: 'j1.3.jpg',
        thumbnail: 'j1.3s.jpg',
      },
      {
        color: ['brown'],
        original: 'j1.4.jpg',
        thumbnail: 'j1.4s.jpg',
      },
    ],
    size: {
      '44': 1,
      '46': 1,
      '48': 1,
      '50': 1,
      '52': 1,
      '54': 1,
    },
    price: 799,
    category: 'jeans',
    globalCategory: 'femaleClothes',
    season: 'autumn/spring',
    createdAt: '2021-09-14T21:39:53.272Z',
    updatedAt: '2021-09-14T21:39:53.272Z',
    __v: 0,
    id: '614116a9a64fb459006d7e35',
  },
  {
    material: ['costumeFabric'],
    popularity: 11,
    title: 'Зеленые зауженные брюки на молнии',
    description:
      'Классические брюки со стрелками. Застёгиваются на молнию, пуговицу и два крючка. Для удобства в носке предусмотрены карманы',
    model: 'model-7',
    color: 'green',
    images: [
      {
        color: ['green'],
        original: 'j1.5.jpg',
        thumbnail: 'j1.5s.jpg',
      },
      {
        color: ['green'],
        original: 'j1.6.jpg',
        thumbnail: 'j1.6s.jpg',
      },
      {
        color: ['green'],
        original: 'j1.7.jpg',
        thumbnail: 'j1.7s.jpg',
      },
      {
        color: ['green'],
        original: 'j1.8.jpg',
        thumbnail: 'j1.8s.jpg',
      },
    ],
    size: {
      '44': 1,
      '46': 1,
      '48': 1,
      '50': 1,
      '52': 1,
      '54': 1,
    },
    price: 799,
    category: 'jeans',
    globalCategory: 'femaleClothes',
    season: 'autumn/spring',
    createdAt: '2021-09-14T21:42:44.017Z',
    updatedAt: '2021-09-14T21:42:44.017Z',
    __v: 0,
    id: '61411754a64fb459006d7e3c',
  },
  {
    material: ['soft'],
    popularity: 11,
    title: 'Блузка прямого кроя с накладными карманами белая',
    description:
      'Сдержанная блузка прямого кроя из софта с отложным воротником. Изделие с накладными карманами на полочке и диагональными клапанами. Застёгивается на пуговицы по планке.',
    model: 'model-8',
    color: 'white',
    images: [
      {
        color: ['white'],
        original: 't1.1.jpg',
        thumbnail: 't1.1s.jpg',
      },
      {
        color: ['white'],
        original: 't1.2.jpg',
        thumbnail: 't1.2s.jpg',
      },
    ],
    size: {
      '44': 1,
      '46': 1,
      '48': 1,
      '50': 1,
    },
    price: 799,
    category: 'shirts',
    globalCategory: 'femaleClothes',
    season: 'autumn/spring',
    createdAt: '2021-09-14T21:47:44.174Z',
    updatedAt: '2021-09-14T21:47:44.174Z',
    __v: 0,
    id: '61411880a64fb459006d7e41',
  },
  {
    material: ['crepe'],
    popularity: 9,
    title: 'Зеленое платье батал с декоративной молнией',
    description: 'Платье асимметричного кроя с декоративной молнией. Спинка изделия дополнена шлицей.',
    model: 'model-9',
    color: 'green',
    images: [
      {
        color: ['green'],
        original: 'b1.1.jpg',
        thumbnail: 'b1.1s.jpg',
      },
      {
        color: ['green'],
        original: 'b1.2.jpg',
        thumbnail: 'b1.2s.jpg',
      },
    ],
    size: {
      '48': 1,
      '50': 1,
      '52': 0,
      '54': 0,
      '56': 1,
      '58': 1,
    },
    price: 799,
    category: 'largeSizes',
    globalCategory: 'femaleClothes',
    season: 'autumn/spring',
    createdAt: '2021-09-14T21:52:30.677Z',
    updatedAt: '2021-09-19T14:23:10.588Z',
    __v: 0,
    id: '6141199ea64fb459006d7e44',
  },
  {
    material: ['guipure'],
    popularity: 8,
    title: 'Черное платье батал из гипюра двухслойное',
    description:
      'Двухслойное платье приталенного силуэта с короткими рукавами. Застегивается на молнию сзади.На модели представлен 50 размер',
    model: 'model-10',
    color: 'black',
    images: [
      {
        color: ['black'],
        original: 'b2.1.jpg',
        thumbnail: 'b2.1s.jpg',
      },
      {
        color: ['black'],
        original: 'b2.2.jpg',
        thumbnail: 'b2.2s.jpg',
      },
    ],
    size: {
      '48': 1,
      '50': 1,
      '52': 1,
      '54': 0,
    },
    price: 799,
    category: 'largeSizes',
    globalCategory: 'femaleClothes',
    season: 'autumn/spring',
    createdAt: '2021-09-14T21:57:23.300Z',
    updatedAt: '2021-09-14T21:57:23.300Z',
    __v: 0,
    id: '61411ac3a64fb459006d7e47',
  },
  {
    material: ['guipure'],
    popularity: 7,
    title: 'Темно-синее платье батал из гипюра двухслойное',
    description:
      'Двухслойное платье приталенного силуэта с короткими рукавами. Застегивается на молнию сзади.',
    model: 'model-10',
    color: 'blue',
    images: [
      {
        color: ['blue'],
        original: 'b2.3.jpg',
        thumbnail: 'b2.3s.jpg',
      },
      {
        color: ['blue'],
        original: 'b2.4.jpg',
        thumbnail: 'b2.4s.jpg',
      },
      {
        color: ['blue'],
        original: 'b2.5.jpg',
        thumbnail: 'b2.5s.jpg',
      },
    ],
    size: {
      '48': 0,
      '50': 1,
      '52': 0,
      '54': 0,
    },
    price: 1099,
    category: 'largeSizes',
    globalCategory: 'femaleClothes',
    season: 'autumn/spring',
    createdAt: '2021-09-14T21:59:27.177Z',
    updatedAt: '2021-09-14T21:59:27.177Z',
    __v: 0,
    id: '61411b3fa64fb459006d7e4a',
  },
]
