export type { ICategoriesProps, IProductsProps } from './props'
export type {
  Categories,
  IProduct,
  ProductToAdd,
  ICallRequest,
  IDataResponse,
  IState,
  IError,
  FilterOption,
  InitialFilter,
  Request,
  IProductObject,
  IResponse,
  IShotSelectedProducts,
  IShoppingBag,
  FilterQuery,
  ILoginData,
  ProductToUpdate,
  IAdmin,
} from './interfaces'
